name: Hola Fecha!

on:
  push:
    branches:
      - master

jobs:
  saludo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fecha
        run: |
           "La fecha actual es " date +"Year: %Y, Month: %m, Day: %d"
     
